// dupgroup.go groups pending records that are the same recurring alert so
// an operator can confirm the whole burst at once, and keeps the
// duplicates out of RAG retrieval afterwards.
//
// # Why this exists
//
// A single flapping check fills the pending list on its own. On one real
// deployment 40 pending records collapsed into 4 groups: one
// SSLCertExpiringSoon for the same host accounted for 35 of them, firing
// daily for nine days because nobody had time to click through 35
// identical rows. The list being noisy is what stopped it being cleared,
// and an uncleared list meant suppression-candidates (which only reads
// *confirmed* history) never saw the group either — so the one command
// that could have proposed silencing it stayed blind to the loudest thing
// in the system.
//
// # Why the grouping key is (alert_name, host) and not the content
//
// The obvious key is "same text" — hash the summary or the log excerpt
// and group on that. It does not work here, and the reason is worth
// writing down because it is specific to this system:
//
//   - summary is generated by the LLM on every capture, so two firings of
//     the same alert produce different prose.
//   - log_excerpt is whatever the log source returned for that time
//     window, so it differs by construction.
//
// Hashing either one degrades to "every row is its own group" — the
// feature would appear to work and do nothing. (alert_name, host) is also
// already the unit pkg/suppress groups by when it proposes suppression
// rules, so an operator reading both sees the same shape in both places.
//
// # What dup_of does and deliberately does not do
//
// Confirming a group marks every row confirmed and points all but the
// representative at it via dup_of. Search then skips them. It does not
// delete them, hide them from /incidents, or make them stop counting: a
// duplicate is still a record of an alert that really fired. The only
// thing it changes is whether a row is offered back to the LLM as a
// retrieval example — without it, confirming one 35-row group would mean
// every later retrieval competes against 35 near-identical neighbours.
package rag

import (
	"context"
	"database/sql/driver"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// PendingGroup is one (alert_name, host) bucket of pending records.
type PendingGroup struct {
	// RepID is the representative: the newest row in the group. Newest
	// rather than oldest because its log excerpt and summary are the ones
	// most likely to still describe the current state of the problem.
	RepID     int64
	AlertName string
	Host      string
	// Size is how many pending rows are in this group, including RepID.
	Size int
	// Summary is the representative's summary — an unverified LLM guess,
	// same caveat as everywhere else pending summaries are shown.
	Summary   string
	NewestAt  time.Time
	OldestAt  time.Time
	MemberIDs []int64
}

// Span is how long this group has been recurring. Zero for a single-row
// group.
//
// Worth showing next to Size: "12 firings in 90 seconds" is a flapping
// check, "12 firings over nine days" is something nobody is fixing. The
// count alone does not distinguish them.
func (g PendingGroup) Span() time.Duration {
	if g.Size <= 1 {
		return 0
	}
	return g.NewestAt.Sub(g.OldestAt)
}

// HasDupOf reports whether the incidents table has the dup_of column, i.e.
// whether migrate_0003_dup_of.sql (or a schema.sql new enough to include
// it) has been applied.
//
// Callers use this to degrade gracefully instead of failing: an operator
// who upgraded the binary but has not run the migration keeps a working
// pending list, just without batch confirm. Erroring out on a missing
// column would take a working deployment down over an optional feature.
func (s *PGStore) HasDupOf(ctx context.Context) (bool, error) {
	var exists bool
	err := s.db.QueryRowContext(ctx, `
		SELECT EXISTS (
		  SELECT 1 FROM information_schema.columns
		   WHERE table_name = 'incidents' AND column_name = 'dup_of'
		)`).Scan(&exists)
	if err != nil {
		return false, fmt.Errorf("rag check dup_of column: %w", err)
	}
	return exists, nil
}

// ListPendingGroups returns up to limit groups of pending records, the
// most recently active group first.
//
// limit counts *groups*, not rows — a caller showing both numbers should
// call CountPending for the row count rather than summing Size, which
// only covers the groups returned.
func (s *PGStore) ListPendingGroups(ctx context.Context, filter ListFilter, limit int) ([]PendingGroup, error) {
	if limit <= 0 {
		limit = 20
	}
	where := "status = 'pending'"
	args := []any{limit}
	argN := 1
	if filter.AlertName != "" {
		argN++
		where += fmt.Sprintf(" AND alert_name ILIKE $%d", argN)
		args = append(args, "%"+filter.AlertName+"%")
	}
	if filter.Host != "" {
		argN++
		where += fmt.Sprintf(" AND host ILIKE $%d", argN)
		args = append(args, "%"+filter.Host+"%")
	}

	rows, err := s.db.QueryContext(ctx, `
		WITH pend AS (
		  SELECT id, alert_name, host, summary, created_at
		    FROM incidents
		   WHERE `+where+`
		), grp AS (
		  SELECT alert_name, host,
		         count(*)        AS n,
		         max(created_at) AS newest,
		         min(created_at) AS oldest,
		         (array_agg(id ORDER BY created_at DESC, id DESC))[1] AS rep_id,
		         array_agg(id ORDER BY created_at DESC, id DESC)      AS member_ids
		    FROM pend
		   GROUP BY alert_name, host
		)
		SELECT g.rep_id, g.alert_name, g.host, g.n, p.summary,
		       g.newest, g.oldest, g.member_ids
		  FROM grp g
		  JOIN pend p ON p.id = g.rep_id
		 ORDER BY g.newest DESC
		 LIMIT $1
	`, args...)
	if err != nil {
		return nil, fmt.Errorf("rag list pending groups: %w", err)
	}
	defer func() { _ = rows.Close() }()

	var out []PendingGroup
	for rows.Next() {
		var g PendingGroup
		var ids pqInt64Array
		if err := rows.Scan(&g.RepID, &g.AlertName, &g.Host, &g.Size, &g.Summary,
			&g.NewestAt, &g.OldestAt, &ids); err != nil {
			return nil, fmt.Errorf("rag list pending groups scan row: %w", err)
		}
		g.MemberIDs = ids
		out = append(out, g)
	}
	return out, rows.Err()
}

// CountPending returns the total number of pending rows matching filter,
// ignoring any group limit.
func (s *PGStore) CountPending(ctx context.Context, filter ListFilter) (int, error) {
	where := "status = 'pending'"
	var args []any
	argN := 0
	if filter.AlertName != "" {
		argN++
		where += fmt.Sprintf(" AND alert_name ILIKE $%d", argN)
		args = append(args, "%"+filter.AlertName+"%")
	}
	if filter.Host != "" {
		argN++
		where += fmt.Sprintf(" AND host ILIKE $%d", argN)
		args = append(args, "%"+filter.Host+"%")
	}
	var n int
	if err := s.db.QueryRowContext(ctx,
		`SELECT count(*) FROM incidents WHERE `+where, args...).Scan(&n); err != nil {
		return 0, fmt.Errorf("rag count pending: %w", err)
	}
	return n, nil
}

// GroupMemberIDs returns the pending ids in the same (alert_name, host)
// group as repID, representative first.
//
// Only rows created at or before the representative are included. The
// batch form carries just the representative's id, so the server looks
// the group up again at submit time — without this bound, alerts that
// fired between the operator loading the page and pressing the button
// would be confirmed too, and nobody looked at those.
//
// A repID that is no longer pending returns an empty slice, not an error:
// that is what a concurrent confirm looks like, and the caller reports it
// as skipped.
func (s *PGStore) GroupMemberIDs(ctx context.Context, repID int64) ([]int64, error) {
	rows, err := s.db.QueryContext(ctx, `
		WITH rep AS (
		  SELECT alert_name, host, created_at
		    FROM incidents
		   WHERE id = $1 AND status = 'pending'
		)
		SELECT i.id
		  FROM incidents i, rep
		 WHERE i.status = 'pending'
		   AND i.alert_name = rep.alert_name
		   AND i.host = rep.host
		   AND i.created_at <= rep.created_at
		 ORDER BY (i.id = $1) DESC, i.created_at DESC, i.id DESC
	`, repID)
	if err != nil {
		return nil, fmt.Errorf("rag group member ids: %w", err)
	}
	defer func() { _ = rows.Close() }()

	var out []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("rag group member ids scan row: %w", err)
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// ConfirmPendingGroup confirms every still-pending id in ids with the same
// resolution and points all but repID at repID via dup_of. It returns how
// many rows it actually confirmed.
//
// repID must be in ids, or dup_of would point at a row this call did not
// confirm.
//
// Only rows this call actually moved get dup_of set. Rows that were
// already confirmed by someone else are left alone: marking them as
// duplicates of this group would drop a resolution someone else wrote —
// possibly a contradictory one — out of Search with nothing to show that
// it happened.
//
// The representative's own dup_of is cleared, not just left as-is. It may
// have been set by an earlier batch, and a representative that still
// points at an older row would take the whole new group out of Search.
func (s *PGStore) ConfirmPendingGroup(ctx context.Context, ids []int64, resolution string, repID int64) (int, error) {
	if strings.TrimSpace(resolution) == "" {
		return 0, fmt.Errorf("rag confirm pending group: resolution is required")
	}
	if len(ids) == 0 {
		return 0, nil
	}
	if !containsInt64(ids, repID) {
		return 0, fmt.Errorf("rag confirm pending group: representative %d is not in the batch", repID)
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return 0, fmt.Errorf("rag confirm pending group: begin: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	rows, err := tx.QueryContext(ctx, `
		UPDATE incidents
		   SET resolution = $2, status = 'confirmed', confirmed_at = now()
		 WHERE id = ANY($1) AND status = 'pending'
	 RETURNING id
	`, pqInt64Array(ids), resolution)
	if err != nil {
		return 0, fmt.Errorf("rag confirm pending group: update: %w", err)
	}
	var updated []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			_ = rows.Close()
			return 0, fmt.Errorf("rag confirm pending group: scan: %w", err)
		}
		updated = append(updated, id)
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return 0, fmt.Errorf("rag confirm pending group: iterate: %w", err)
	}
	_ = rows.Close()

	if len(updated) == 0 {
		return 0, tx.Commit()
	}

	var dups []int64
	for _, id := range updated {
		if id != repID {
			dups = append(dups, id)
		}
	}
	if len(dups) > 0 {
		if _, err := tx.ExecContext(ctx,
			`UPDATE incidents SET dup_of = $2 WHERE id = ANY($1)`,
			pqInt64Array(dups), repID); err != nil {
			return 0, fmt.Errorf("rag confirm pending group: mark duplicates: %w", err)
		}
	}
	if containsInt64(updated, repID) {
		if _, err := tx.ExecContext(ctx,
			`UPDATE incidents SET dup_of = NULL WHERE id = $1`, repID); err != nil {
			return 0, fmt.Errorf("rag confirm pending group: clear representative dup_of: %w", err)
		}
	}
	if err := tx.Commit(); err != nil {
		return 0, fmt.Errorf("rag confirm pending group: commit: %w", err)
	}
	return len(updated), nil
}

func containsInt64(xs []int64, want int64) bool {
	for _, x := range xs {
		if x == want {
			return true
		}
	}
	return false
}

// pqInt64Array adapts []int64 to and from Postgres bigint[] without
// pulling in a driver-specific array type: pgx's stdlib wrapper accepts
// driver.Valuer on the way in, and hands back either []byte or string on
// the way out depending on the result format.
type pqInt64Array []int64

func (a pqInt64Array) Value() (driver.Value, error) {
	if a == nil {
		return nil, nil
	}
	parts := make([]string, len(a))
	for i, v := range a {
		parts[i] = strconv.FormatInt(v, 10)
	}
	return "{" + strings.Join(parts, ",") + "}", nil
}

func (a *pqInt64Array) Scan(src any) error {
	var s string
	switch v := src.(type) {
	case nil:
		*a = nil
		return nil
	case []byte:
		s = string(v)
	case string:
		s = v
	default:
		return fmt.Errorf("rag: cannot scan %T into int64 array", src)
	}
	s = strings.Trim(s, "{}")
	if s == "" {
		*a = nil
		return nil
	}
	parts := strings.Split(s, ",")
	out := make([]int64, 0, len(parts))
	for _, p := range parts {
		n, err := strconv.ParseInt(strings.TrimSpace(p), 10, 64)
		if err != nil {
			return fmt.Errorf("rag: bad int64 array element %q: %w", p, err)
		}
		out = append(out, n)
	}
	*a = out
	return nil
}
